-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 23:19:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema radostan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema radostan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `radostan` DEFAULT CHARACTER SET utf8mb3 ;
USE `radostan` ;

-- -----------------------------------------------------
-- Table `radostan`.`grejanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`grejanje` (
  `idGrejanje` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrejanje`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`stanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`stanje` (
  `idStanje` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStanje`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`tip` (
  `idTip` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`nekretnina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`nekretnina` (
  `idNekretnina` INT NOT NULL AUTO_INCREMENT,
  `idTip` INT NOT NULL,
  `idStanja` INT NOT NULL,
  `kvadratura` DOUBLE NOT NULL,
  `drzava` VARCHAR(45) NOT NULL,
  `grad` VARCHAR(45) NOT NULL,
  `opstina` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `idGrejanja` INT NOT NULL,
  `opis` VARCHAR(300) NULL DEFAULT NULL,
  `broj_soba` DOUBLE NOT NULL,
  `cena` DOUBLE NOT NULL,
  PRIMARY KEY (`idNekretnina`),
  INDEX `FK_idStanja_Stanje_idx` (`idStanja` ASC) VISIBLE,
  INDEX `FK_idTip_Tip_idx` (`idTip` ASC) VISIBLE,
  INDEX `FK_idGrejanja_Grejanje_idx` (`idGrejanja` ASC) VISIBLE,
  CONSTRAINT `FK_idGrejanja_Grejanje`
    FOREIGN KEY (`idGrejanja`)
    REFERENCES `radostan`.`grejanje` (`idGrejanje`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_idStanja_Stanje`
    FOREIGN KEY (`idStanja`)
    REFERENCES `radostan`.`stanje` (`idStanje`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_idTip_Tip`
    FOREIGN KEY (`idTip`)
    REFERENCES `radostan`.`tip` (`idTip`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`oprema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`oprema` (
  `idOprema` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOprema`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`ima_oprema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`ima_oprema` (
  `idNekretnina` INT NOT NULL,
  `idOprema` INT NOT NULL,
  PRIMARY KEY (`idNekretnina`, `idOprema`),
  INDEX `fk_imaoprema_nekretnina1_idx` (`idNekretnina` ASC) VISIBLE,
  INDEX `fk_imaoprema_oprema1_idx` (`idOprema` ASC) VISIBLE,
  CONSTRAINT `fk_imaoprema_nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`),
  CONSTRAINT `fk_imaoprema_oprema1`
    FOREIGN KEY (`idOprema`)
    REFERENCES `radostan`.`oprema` (`idOprema`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`ima_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`ima_tag` (
  `idTag` INT NOT NULL,
  `idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idTag`, `idNekretnina`),
  INDEX `fk_imatag_tag1_idx` (`idTag` ASC) VISIBLE,
  INDEX `fk_imatag_nekretnina1_idx` (`idNekretnina` ASC) VISIBLE,
  CONSTRAINT `fk_imatag_nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`),
  CONSTRAINT `fk_imatag_tag1`
    FOREIGN KEY (`idTag`)
    REFERENCES `radostan`.`tag` (`idTag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime_prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`je_omiljeni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`je_omiljeni` (
  `idKorisnik` INT NOT NULL,
  `idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`, `idNekretnina`),
  INDEX `fk_omiljeni_korisnik1_idx` (`idKorisnik` ASC) VISIBLE,
  INDEX `fk_omiljeni_nekretnina1_idx` (`idNekretnina` ASC) VISIBLE,
  CONSTRAINT `fk_omiljeni_korisnik1`
    FOREIGN KEY (`idKorisnik`)
    REFERENCES `radostan`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_omiljeni_nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`prodaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`prodaje` (
  `idKorisnik` INT NOT NULL,
  `idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`, `idNekretnina`),
  INDEX `fk_prodaje_korisnik1_idx` (`idKorisnik` ASC) VISIBLE,
  INDEX `fk_prodaje_nekretnina1_idx` (`idNekretnina` ASC) VISIBLE,
  CONSTRAINT `fk_prodaje_korisnik1`
    FOREIGN KEY (`idKorisnik`)
    REFERENCES `radostan`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_prodaje_nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`slike_nekretnina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`slike_nekretnina` (
  `idSlika` INT NOT NULL AUTO_INCREMENT,
  `idNekretnina` INT NOT NULL,
  `slika` BLOB NOT NULL,
  PRIMARY KEY (`idSlika`),
  INDEX `FK_idNekretnina_Nekretnina_idx` (`idNekretnina` ASC) VISIBLE,
  CONSTRAINT `FK_idNekretnina_Nekretnina`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`zahtev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`zahtev` (
  `idZahtev` INT NOT NULL AUTO_INCREMENT,
  `ime_prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZahtev`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
