-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 23:19:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema radostan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema radostan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `radostan` DEFAULT CHARACTER SET utf8mb3 ;
USE `radostan` ;

-- -----------------------------------------------------
-- Table `radostan`.`grejanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`grejanje` (
  `idGrejanja` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrejanja`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`stanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`stanje` (
  `idStanja` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStanja`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`tip` (
  `idTip` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;





-- -----------------------------------------------------
-- Table `radostan`.`oprema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`oprema` (
  `idOprema` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOprema`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `radostan`.`nekretnina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`nekretnina` (
  `idNekretnina` INT NOT NULL AUTO_INCREMENT,
  `idTip` INT NOT NULL,
  `idStanja` INT NOT NULL,
  `kvadratura` DOUBLE NOT NULL,
  `drzava` VARCHAR(45) NOT NULL,
  `grad` VARCHAR(45) NOT NULL,
  `opstina` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `idGrejanja` INT NOT NULL,
  `opis` VARCHAR(300) NULL DEFAULT NULL,
  `broj_soba` DOUBLE NOT NULL,
  `cena` DOUBLE NOT NULL,
  PRIMARY KEY (`idNekretnina`),
  INDEX `FK_idStanja_Stanje_idx` (`idStanja` ASC) ,
  INDEX `FK_idTip_Tip_idx` (`idTip` ASC) ,
  INDEX `FK_idGrejanja_Grejanje_idx` (`idGrejanja` ASC),
  CONSTRAINT `FK_idGrejanja_Grejanje`
    FOREIGN KEY (`idGrejanja`)
    REFERENCES `radostan`.`grejanje` (`idGrejanja`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_idStanja_Stanje`
    FOREIGN KEY (`idStanja`)
    REFERENCES `radostan`.`stanje` (`idStanja`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_idTip_Tip`
    FOREIGN KEY (`idTip`)
    REFERENCES `radostan`.`tip` (`idTip`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `radostan`.`ima_oprema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`ima_oprema` (
  `idNekretnina` INT NOT NULL,
  `idOprema` INT NOT NULL,
  PRIMARY KEY (`idNekretnina`, `idOprema`),
  INDEX `fk_imaoprema_nekretnina1_idx` (`idNekretnina` ASC) ,
  INDEX `fk_imaoprema_oprema1_idx` (`idOprema` ASC) ,
  CONSTRAINT `fk_imaoprema_nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`),
  CONSTRAINT `fk_imaoprema_oprema1`
    FOREIGN KEY (`idOprema`)
    REFERENCES `radostan`.`oprema` (`idOprema`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`ima_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`ima_tag` (
  `idTag` INT NOT NULL,
  `idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idTag`, `idNekretnina`),
  INDEX `fk_imatag_tag1_idx` (`idTag` ASC),
  INDEX `fk_imatag_nekretnina1_idx` (`idNekretnina` ASC),
  CONSTRAINT `fk_imatag_nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`),
  CONSTRAINT `fk_imatag_tag1`
    FOREIGN KEY (`idTag`)
    REFERENCES `radostan`.`tag` (`idTag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime_prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`je_omiljeni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`je_omiljeni` (
  `idKorisnik` INT NOT NULL,
  `idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`, `idNekretnina`),
  INDEX `fk_omiljeni_korisnik1_idx` (`idKorisnik` ASC) ,
  INDEX `fk_omiljeni_nekretnina1_idx` (`idNekretnina` ASC) ,
  CONSTRAINT `fk_omiljeni_korisnik1`
    FOREIGN KEY (`idKorisnik`)
    REFERENCES `radostan`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_omiljeni_nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`prodaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`prodaje` (
  `idKorisnik` INT NOT NULL,
  `idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`, `idNekretnina`),
  INDEX `fk_prodaje_korisnik1_idx` (`idKorisnik` ASC) ,
  INDEX `fk_prodaje_nekretnina1_idx` (`idNekretnina` ASC) ,
  CONSTRAINT `fk_prodaje_korisnik1`
    FOREIGN KEY (`idKorisnik`)
    REFERENCES `radostan`.`korisnik` (`idKorisnik`),
  CONSTRAINT `fk_prodaje_nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`slike_nekretnina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`slike_nekretnina` (
  `idSlika` INT NOT NULL AUTO_INCREMENT,
  `idNekretnina` INT NOT NULL,
  `slika` LONGBLOB NOT NULL,
  PRIMARY KEY (`idSlika`),
  INDEX `FK_idNekretnina_Nekretnina_idx` (`idNekretnina` ASC) ,
  CONSTRAINT `FK_idNekretnina_Nekretnina`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `radostan`.`nekretnina` (`idNekretnina`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `radostan`.`zahtev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radostan`.`zahtev` (
  `idZahtev` INT NOT NULL AUTO_INCREMENT,
  `ime_prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZahtev`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

/*
INSERT INTO tip(naziv) VALUES('stan'), ('kuca'), ('plac');
INSERT INTO stanje(naziv) VALUES('novo'), ('za rusenje'), ('stara gradnja');
INSERT INTO grejanje(naziv) VALUES('centralno'), ('podno'), ('gas'),('struja'), ('pelet');


INSERT INTO `nekretnina` (`idNekretnina`, `idTip`, `idStanja`, `kvadratura`, `drzava`, `grad`, `opstina`, `adresa`, `idGrejanja`, `opis`, `broj_soba`, `cena`) VALUES
(1, 1, 1, 90, 'Srbija', 'Beograd', 'Novi Beograd Blok 33 (Genex kula)', '-', 1, 'BLOK 33, TROIPOSOBAN, 90M2, UKNJIZEN', 4, 195000),
(2, 1, 1, 57, 'Srbija', 'Beograd', 'Borča I', '-', 1, 'BORCA GREDA, 57M2, CG, USELJIV', 2, 75000),
(3, 1, 1, 46.8, 'Srbija', 'Novi Sad', 'Veternik', '-', 1, 'Novi Sad, Veternik, Lep dvoiposoban stan u izgradnji sa povratom pdv-a', 2, 81946),
(4, 1, 1, 81.04, 'Srbija', 'Novi Sad', 'Adice', '-', 1, 'Novi Sad, Telepska dolina - blizu Dunava, Odličan 3.5 stan sa povratom pdv-a -može na kredit-useljiv odmah', 4, 129380),
(5, 1, 1, 108, 'Srbija', 'Novi Sad', 'Liman 4', '-', 1, 'Novi Sad, Bulevar Patrijarha Pavla, lux penthouse sa dodatnom krovnom terasom u lux zgradi', 3, 310000),
(6, 1, 1, 34.15, 'Srbija', 'Novi Sad', 'Veternik', '-', 1, 'Novi Sad, Veternik, jednoiposoban stan u izgradnji sa povratom pdv-a - useljenje jul 2023. godine', 1, 61554),
(7, 1, 1, 45.6, 'Srbija', 'Novi Sad', 'Podbara', '-', 1, 'Novi Sad, Podbara- centar, Renoviran dvosoban stan u pasazu- moguce prosirenje u potkrovlju', 2, 87650),
(8, 1, 1, 40.65, 'Srbija', 'Novi Sad', 'Veternik', '-', 1, 'Novi Sad, Veternik, dvoiposoban stan u izgradnji sa povratom pdv-a - useljenje jul 2023. godine', 2, 71178),
(9, 1, 1, 75.15, 'Srbija', 'Novi Sad', 'Veternik', '-', 1, 'Novi Sad, Veternik, četvorosoban stan u izgradnji sa povratom pdv-a - useljenje jul 2023. godine', 4, 100625),
(10, 1, 1, 57, 'Srbija', 'Novi Sad', 'Bulevar', '-', 1, 'Novi Sad, Bulevar Evrope, lux trosoban  stan', 3, 650),
(11, 1, 1, 60, 'Srbija', 'Novi Sad', 'Adamovićevo naselje', '-', 1, 'Novi Sad, Futoški put, Lux trosoban  stan u urbanoj vili - useljiv u junu 2023. god', 3, 135000),
(12, 1, 1, 53.79, 'Srbija', 'Novi Sad', 'Podbara', '-', 1, 'Novi Sad, Podbara - Centar, Odličan dvoiposoban stan sa povratom PDV-a- useljiv u decembru 2023.', 2, 132960),
(13, 1, 1, 53, 'Srbija', 'Novi Sad', 'Adamovićevo naselje', '-', 1, 'Novi Sad, Cara Dusana, Potpuno renoviran dvosoban stan sa odvojenom kuhinjom', 2, 103000),
(14, 1, 1, 79.9, 'Srbija', 'Novi Sad', 'Petrovaradin', '-', 1, 'Novi Sad, Petrovaradin, Lux četvorosoban stan sa povratom PDV-a - useljiv odmah!', 4, 164590),
(15, 1, 1, 60, 'Srbija', 'Novi Sad', 'Adamovićevo naselje', '-', 1, 'Novi Sad, Futoški put, Lux trosoban  stan u urbanoj vili - useljiv u junu 2023. god', 3, 135000),
(16, 1, 1, 42, 'Srbija', 'Novi Sad', 'Bulevar', '-', 1, 'Novi Sad, Bulevar oslobođenja, Odličan stan na idealnoj lokaciji', 1, 89600),
(17, 1, 1, 58, 'Srbija', 'Novi Sad', 'Detelinara nova', '-', 1, 'Nova Detelinara, Nov, neuseljavan dvoiposoban stan-odlicna lokacija', 2, 400),
(18, 1, 1, 45, 'Srbija', 'Novi Sad', 'Podbara', '-', 1, 'Novi Sad, Podbara, Odličan namešten stan u novijoj zgradi- blizu centra', 1, 129780),
(19, 1, 1, 47, 'Srbija', 'Novi Sad', 'Grbavica', '-', 1, 'Novi Sad, Grbavica, Uknjižen stan u sirovom stanju', 1, 71790),
(20, 1, 1, 90, 'Srbija', 'Beograd', 'Novi Beograd Blok 33 (Genex kula)', '-', 1, 'BLOK 33, TROIPOSOBAN, 90M2, UKNJIZEN', 4, 195000),
(21, 1, 1, 57, 'Srbija', 'Beograd', 'Borča I', '-', 1, 'BORCA GREDA, 57M2, CG, USELJIV', 2, 75000),
(22, 1, 1, 46.8, 'Srbija', 'Novi Sad', 'Veternik', '-', 1, 'Novi Sad, Veternik, Lep dvoiposoban stan u izgradnji sa povratom pdv-a', 2, 81946),
(23, 1, 1, 81.04, 'Srbija', 'Novi Sad', 'Adice', '-', 1, 'Novi Sad, Telepska dolina - blizu Dunava, Odličan 3.5 stan sa povratom pdv-a -može na kredit-useljiv odmah', 4, 129380),
(24, 1, 1, 108, 'Srbija', 'Novi Sad', 'Liman 4', '-', 1, 'Novi Sad, Bulevar Patrijarha Pavla, lux penthouse sa dodatnom krovnom terasom u lux zgradi', 3, 310000),
(25, 1, 1, 34.15, 'Srbija', 'Novi Sad', 'Veternik', '-', 1, 'Novi Sad, Veternik, jednoiposoban stan u izgradnji sa povratom pdv-a - useljenje jul 2023. godine', 1, 61554),
(26, 1, 1, 45.6, 'Srbija', 'Novi Sad', 'Podbara', '-', 1, 'Novi Sad, Podbara- centar, Renoviran dvosoban stan u pasazu- moguce prosirenje u potkrovlju', 2, 87650),
(27, 1, 1, 40.65, 'Srbija', 'Novi Sad', 'Veternik', '-', 1, 'Novi Sad, Veternik, dvoiposoban stan u izgradnji sa povratom pdv-a - useljenje jul 2023. godine', 2, 71178),
(28, 1, 1, 75.15, 'Srbija', 'Novi Sad', 'Veternik', '-', 1, 'Novi Sad, Veternik, četvorosoban stan u izgradnji sa povratom pdv-a - useljenje jul 2023. godine', 4, 100625),
(29, 1, 1, 57, 'Srbija', 'Novi Sad', 'Bulevar', '-', 1, 'Novi Sad, Bulevar Evrope, lux trosoban  stan', 3, 650),
(30, 1, 1, 60, 'Srbija', 'Novi Sad', 'Adamovićevo naselje', '-', 1, 'Novi Sad, Futoški put, Lux trosoban  stan u urbanoj vili - useljiv u junu 2023. god', 3, 135000),
(31, 1, 1, 53.79, 'Srbija', 'Novi Sad', 'Podbara', '-', 1, 'Novi Sad, Podbara - Centar, Odličan dvoiposoban stan sa povratom PDV-a- useljiv u decembru 2023.', 2, 132960),
(32, 1, 1, 53, 'Srbija', 'Novi Sad', 'Adamovićevo naselje', '-', 1, 'Novi Sad, Cara Dusana, Potpuno renoviran dvosoban stan sa odvojenom kuhinjom', 2, 103000),
(33, 1, 1, 79.9, 'Srbija', 'Novi Sad', 'Petrovaradin', '-', 1, 'Novi Sad, Petrovaradin, Lux četvorosoban stan sa povratom PDV-a - useljiv odmah!', 4, 164590),
(34, 1, 1, 60, 'Srbija', 'Novi Sad', 'Adamovićevo naselje', '-', 1, 'Novi Sad, Futoški put, Lux trosoban  stan u urbanoj vili - useljiv u junu 2023. god', 3, 135000),
(35, 1, 1, 42, 'Srbija', 'Novi Sad', 'Bulevar', '-', 1, 'Novi Sad, Bulevar oslobođenja, Odličan stan na idealnoj lokaciji', 1, 89600),
(36, 1, 1, 58, 'Srbija', 'Novi Sad', 'Detelinara nova', '-', 1, 'Nova Detelinara, Nov, neuseljavan dvoiposoban stan-odlicna lokacija', 2, 400),
(37, 1, 1, 45, 'Srbija', 'Novi Sad', 'Podbara', '-', 1, 'Novi Sad, Podbara, Odličan namešten stan u novijoj zgradi- blizu centra', 1, 129780),
(38, 1, 1, 47, 'Srbija', 'Novi Sad', 'Grbavica', '-', 1, 'Novi Sad, Grbavica, Uknjižen stan u sirovom stanju', 1, 71790),
(39, 1, 1, 24, 'Srbija', 'Novi Sad', 'Sajlovo', '-', 1, 'Novi Sad, Sajlovo, Nova garsonjera sa parkingom i terasom u dvorištu', 0, 45000),
(40, 1, 1, 90, 'Srbija', 'Beograd', 'Novi Beograd Blok 33 (Genex kula)', '-', 2, 'BLOK 33, TROIPOSOBAN, 90M2, UKNJIZEN', 4, 195000),
(41, 1, 1, 57, 'Srbija', 'Beograd', 'Borča I', '-', 1, 'BORCA GREDA, 57M2, CG, USELJIV', 2, 75000),
(42, 1, 1, 283, 'Srbija', 'Beograd', 'Vračar (Hram)', '-', 1, 'Duplex-penthaus,Patrijarha Varnave,283m2+2PM ID#1476', 5, 1130000),
(43, 1, 1, 63, 'Srbija', 'Beograd', 'Vračar (Centar)', '-', 1, 'Kneginje Zorke, 2.0,63m2,lift,CG ID#1459', 2, 145000),
(44, 1, 1, 152, 'Srbija', 'Beograd', 'Novi Beograd Blok 58', '-', 1, 'Luksuzan 4.0 Penthouse / SAKURA', 4, 2900),
(45, 1, 1, 61, 'Srbija', 'Beograd', 'Zemun (Meandri)', '-', 2, 'Zemun, Prvomajska, 2.0 stan sa pogledom, brzo useljiv ID#8618', 2, 110000),
(46, 1, 1, 104, 'Srbija', 'Beograd', 'Zvezdara', '-', 1, 'Odlična prilika, Zvezdara, Vojislava Ilića, 104m2', 3, 188100),
(47, 1, 1, 104, 'Srbija', 'Beograd', 'Lekino brdo', '-', 1, 'Lekino brdo, Garibaldijeva 104m2 sa 3 parking mesta', 3, 290000),
(48, 1, 1, 55, 'Srbija', 'Beograd', 'Autokomanda', '-', 1, 'Voždovac, Vojvode Stepe 55m2 + terasa', 2, 148500),
(49, 1, 1, 120, 'Srbija', 'Beograd', 'Petlovo brdo', '-', 1, 'Petlovo brdo, 120m2', 5, 134000),
(50, 1, 1, 41, 'Srbija', 'Beograd', 'Kotež', '-', 1, 'Kotež, kod okretnice autobusa, 41m2', 2, 67650),
(51, 1, 1, 55, 'Srbija', 'Beograd', 'Donji Dorćol', '-', 1, 'Lux 2.0 - garaza / polunamesten- K DISTRIKT', 2, 1200),
(52, 1, 1, 54, 'Srbija', 'Beograd', 'Lion', '-', 2, 'Zvezdara teatar, Lion, Radoja Domanovića 54m2 2 identicna stana', 2, 149000),
(53, 1, 1, 70, 'Srbija', 'Beograd', 'Altina', '-', 1, 'Izdajem stan', 3, 600),
(54, 1, 1, 47, 'Srbija', 'Beograd', 'Crveni krst', '-', 1, 'Crveni krst, Vojislava Ilića, 47m2', 2, 136000),
(55, 1, 1, 35, 'Srbija', 'Beograd', 'Stepa Stepanović', '-', 1, 'Stepa Stepanović- Novogradnja 35m2', 1, 96500),
(56, 1, 1, 96, 'Srbija', 'Beograd', 'Novi Beograd', '-', 1, 'Novi Beograd, Blok 4, stan, 96m2 (+8m2 terasa)', 4, 270000),
(57, 1, 1, 50, 'Srbija', 'Beograd', 'Beograd na vodi', '-', 1, 'BW Metropolitan, Beograd na vodi, 50m2, sa parking mestom', 2, 1350),
(58, 1, 1, 43, 'Srbija', 'Beograd', 'Medaković III', '-', 1, 'Medak - Dr Čedomira Đurđevića 43m2', 2, 91000),
(59, 1, 1, 45, 'Srbija', 'Beograd', 'Braće Jerković', '-', 2, 'Braće Jerković - Mitrovdanska 45m2', 1, 90000);
*/

INSERT INTO `nekretnina` (kvadratura, drzava, grad, opstina, adresa, opis, broj_soba, cena, idTip, idStanja, idGrejanja)
VALUES
    (468.0, 'Srbija', 'Beograd', 'Sremčica', '-', 'Beograd, Sremčica, Novija dvojna kuća na velikom placu od 1511 m2 u mirnoj ulici - idealno za bazen', 6, 198790.0, 1, 1, 1),
    (300.0, 'Srbija', 'Novi Sad', 'Veternik', '-', 'Novi Sad, Veternik, Lepo uređena kuća - vila na odličnoj lokaciji', 6, 329600.0, 1, 1, 1),
    (600.0, 'Srbija', 'Niš', 'Ćalije', '-', 'Lux kuće, 6. stambnih jedinica, Dva objekta, 4. parking mesta, Poslovni prostor, Novogradnja', 6, 600000.0, 1, 1, 1),
    (560.0, 'Srbija', 'Beograd', 'Radiofar', '-', 'Objekat u izgradnji na 15ari placa od 410m2+30m2+120m2+bazen (u legaliz.)', 6, 290000.0, 1, 1, 1),
    (156.0, 'Srbija', 'Beograd', 'Braće Jerković', '-', 'Voždovac, Braće Jerković - Milovana Jankovića, 156m2 (250m2), Milovana Jankovića', 6, 390000.0, 1, 1, 1),
    (626.0, 'Srbija', 'Beograd', 'Zemun (Novi Grad)', '-', 'Zemun, Novi grad - Geteova, 626m2, Geteova', 6, 370000.0, 1, 1, 1),
    (103.0, 'Srbija', 'Beograd', 'Surčin', '-', 'Surčin, Boljevci - Braće Gavrajić, 103m2, Braće Gavrajić', 6, 67900.0, 1, 1, 1),
    (260.0, 'Srbija', 'Beograd', 'Voždovac', '-', 'Voždovac, Voždovačka crkva - Jove Ilića , 260m2, Jove Ilića', 6, 3200.0, 1, 1, 1),
    (110.0, 'Srbija', 'Beograd', 'Grocka', '-', 'Grocka, Vrčin, -, Kuća, 110m2, 2500 EUR', 6, 2500.0, 1, 1, 1),
    (370.0, 'Srbija', 'Beograd', 'Palilula', '-', 'Prelepo imanje 63 ara sa ribnjakom i jezerom, porodična kuća i poslovni objekat,otvoreni bazen', 6, 1150000.0, 1, 1, 1),
    (350.0, 'Srbija', 'Beograd', 'Senjak', '-', 'Senjak, zasebna kuća,prelepa bašta,dve garaže', 6, 5000.0, 1, 1, 1),
    (400.0, 'Srbija', 'Niš', 'Branko Bjegović', '-', 'Odlična kuća, 400 m2,  na  prelepom  placu  od 730 m2,  Branko  Bjegović', 6, 179000.0, 1, 1, 1),
    (210.0, 'Srbija', 'Beograd', 'Sopot', '-', 'Sopot, Ralja, spratna kuća na 20 ari placa ID#8432', 6, 80000.0, 1, 1, 1),
    (160.0, 'Srbija', 'Beograd', 'Surčin', '-', 'Surčin - Jakovo, kuća sa jedinstvenim placem', 6, 82000.0, 1, 1, 1),
    (170.0, 'Srbija', 'Beograd', 'Bežanijska kosa I', '-', 'Kuća u nizu na Bežanijskoj Kosi I - IZDAJE SE', 6, 2100.0, 1, 1, 1),
    (81.0, 'Srbija', 'Leskovac', 'Kumalak', '-', 'Na prodaju kuća, 81m2, plac 437m2, može zamena za stan', 6, 49500.0, 1, 1, 1),
    (272.0, 'Srbija', 'Beograd', 'Surčin', '-', 'VILA SA BAZENOM', 6, 302000.0, 1, 1, 1);




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
